name: "Chromatic Stage Deployment"

on:
  push:
    branches:
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev-chromatic:
    uses: ./.github/workflows/deploy-chromatic.yaml
    secrets: inherit
    with:
      env: stage
