name: "Chromatic Dev Deployment"

on:
  push:
    branches:
      - dev/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev-chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: deploy-dev-chromatic
        uses: ./.github/workflows/deploy-chromatic.yaml
        with:
          chromaticToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_DEV }}
